name: deploy to aliyun oss

on:
  push:
  schedule:
  - cron:  '30 20 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # 切代码到 runner
    
    - run: |
        free -h
    - run: ls -lah
    - uses: actions/checkout@v1
      with:
        submodules: true
    - run: ls -lah
    # 下载 git submodule
    - uses: srt32/git-actions@v0.0.3
      with:
        args: git submodule update --init --recursive

    # 设置阿里云OSS的 id/secret，存储到 github 的 secrets 中
    - name: setup aliyun oss
      uses: manyuanrong/setup-ossutil@master
      with:
        endpoint: oss-cn-zhangjiakou.aliyuncs.com
        access-key-id: ${{ secrets.OSS_KEY_ID }}
        access-key-secret: ${{ secrets.OSS_KEY_SECRET }}
    
    - name: 复制文件到阿里云OSS
      run: ossutil cp -rf public oss://mist-blog/

